@startuml

class PeerConnectionFactory{
    - class InitializationOptions

    + initialize()
    + PeerConnectionFactory()

    + createPeerConnection()
    + createPeerConnection()
    + createLocalMediaStream()
    + createVideoSource()
    + createVideoTrack()
    + createAudioSource()
    + createAudioTrack()
    + startAecDump()

}

class VideoFrame
interface VideoFrame.Buffer
interface I420Buffer
class JavaI420Buffer implements I420Buffer
interface I420Buffer extends VideoFrame.Buffer
class NV12Buffer implements VideoFrame.Buffer
class NV21Buffer implements VideoFrame.Buffer
interface TextureBuffer extends VideoFrame.Buffer

class MediaSource
class VideoTrack extends MediaStreamTrack
class AudioTrack extends MediaStreamTrack
class MediaStream{
    audioTracks
    videoTracks
    preservedVideoTracks
}


PeerConnectionFactory o-left MediaStream : 实现
MediaStream o-left VideoTrack : 实现
MediaStream o-- AudioTrack : 实现


interface VideoCapturer{
    initialize()
    startCapture()
    stopCapture()
    changeCaptureFormat()
    dispose()
    isScreencast()
}
interface VideoCapturer.CapturerObserver
class ScreenCapturerAndroid implements VideoCapturer, SurfaceTextureHelper.OnTextureFrameAvailableListener


class SurfaceTextureHelper
class SurfaceTextureHelper.OnTextureFrameAvailableListener


@enduml